

TRAITS_DICT:dict[str, dict] = {
    "extroversion":{
        "-1":"introvert",
        "0":"",
        "1":"outgoing"
    },
    "positivity":{
        "-1":"negative",
        "0":"",
        "1":"positive"
    },
    "serenity":{
        "-1":"intense",
        "0":"",
        "1":"serene"
    },
    "courage":{
        "-1":"coward",
        "0":"",
        "1":"brave"
    },
    "charisma":{
        "-1":"shy",
        "0":"",
        "1":"charismatic"
        },
    "sincerity":{
        "-1":"liar",
        "0":"",
        "1":"sincere"
    },
    "peacefulness":{
        "-1":"violent",
        "0":"",
        "1":"peaceful"
    },
    "knowledge":{
        "-1":"illiterate",
        "0":"",
        "1":"intellectual"
    },
    "resistance":{
        "-1":"fragile",
        "0":"",
        "1":"resistant"
    },
    "loyalty":{
        "-1":"treacherous",
        "0":"",
        "1":"loyal"
    },
    "kindness":{
        "-1":"selfish",
        "0":"",
        "1":"kindly"
    },
    "tolerance":{
        "-1":"intolerant",
        "0":"",
        "1":"tolerant"
    },"discipline":{
        "-1":"disorderly",
        "0":"",
        "1":"disciplined"
    },"independence":{
        "-1":"dependent",
        "0":"",
        "1":"independent"
    },"dominance":{
        "-1":"submissive",
        "0":"",
        "1":"dominant"
    },"justice":{
        "-1":"criminal",
        "0":"",
        "1":"fair"
    },"ambition":{
        "-1":"conformist",
        "0":"",
        "1":"ambitious"
    },"self-confidence":{
        "-1":"unsure of himself",
        "0":"",
        "1":"self-confident"
    },"patience":{
        "-1":"impulsive",
        "0":"",
        "1":"patient"
    },"responsability":{
        "-1":"irresponsible",
        "0":"",
        "1":"responsible"
    },"intimacy":{
        "-1":"uninhibited",
        "0":"",
        "1":"reserved"
    },"indulgence":{
        "-1":"rancorous",
        "0":"",
        "1":"indulgent"
    },"adaptability":{
        "-1":"misfit",
        "0":"",
        "1":"adaptable"
    },"beauty":{
        "-1":"ugly",
        "0":"",
        "1":"beautiful"
    },"wealth":{
        "-1":"poor",
        "0":"",
        "1":"rich"
    },"reputation":{
        "-1":"despised",
        "0":"",
        "1":"prestigious"
    },"intelligence":{
        "-1":"silly",
        "0":"",
        "1":"cunning"
    },"force":{
        "-1":"weak",
        "0":"",
        "1":"strong"
    }
}